baseURL = "http://localhost/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Your Photographer'
    weight = 1

  [languages.uk]
    contentDir = 'content/uk'
    languageCode = 'uk-UA'
    languageName = 'Українська'
    title = 'Ваш фотограф'
    weight = 2


[outputs]
    home = ['html', 'json']
    page = ['html']
    rss = ['rss']
    section = ['html']
    taxonomy = ['html']
    term = ['html']

disableAliases = true
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false

[Menus]
    [[Menus.main]]
        identifier = "dropdown"
        title = "galleryDropdownTitle"
        name = "galleryDropdownName"
        weight = 1
    [[Menus.main]]
        identifier = "oc_dropdown1"
        title = "orangeCatsDropdownTitle"
        name = "orangeCatsDropdownName"
        url = "/gallery/orange_cats/"
        parent = "dropdown"
        weight = 1
    [[Menus.main]]
        identifier = "col_dropdown2"
        title = "coolOrangeCatsDropdownTitle"
        name = "coolOrangeCatsDropdownName"
        url = "/gallery/cool_orange_cats/"
        parent = "dropdown"
        weight = 2

[params]
    description = "Cool site"
    favicon = "/logo.png"

    useBootstrapCDN = false
    animate = true

    [params.font]
        fontSize = "1rem"
        fontWeight = 400
        lineHeight = 1.5
        textAlign = "left"

    [params.color]
        textColor = "#343a40"
        secondaryTextColor = "#6c757d"
        textLinkColor = "#007bff"
        backgroundColor = "#eaedf0"
        secondaryBackgroundColor = "#64ffda1a"
        primaryColor = "#007bff"
        secondaryColor = "#f8f9fa"

    [params.navbar]
        align = "ms-auto"
        brandLogo = "/logo.png"
        brandName = "Your Photograph"
        [params.navbar.stickyNavBar]
            enable = true
            showOnScrollUp = true
        enableSeparator = false
        [params.navbar.menus]
            disableAbout = false
            disableKind_words = false
            disableContact = false

    [params.hero]
        enable = true
        intro = "Hi, i am"
        title = "Cat."
        subtitle = "I am your cat"
        content = "A cool cat"
        image = "/images/hero.png"
        [params.hero.bottomImage]
            enable = true

    [params.about]
        enable = true
        title = "About Me"
        image = "/images/me.png"
        content = "Cool catCool catCool catCool catCool catCool catCool catCool cat\nCool catCool catCool cat\nCool catCool catCool catCool catCool catCool catCool catCool catCool cat"
        [params.about.skills]
            enable = true
            title = "\nHere are a few cat I am been working with:"
            items = ["Dark cat", "Light cat", "Orange cat"]

    [params.kind_words]
        enable = true
        title = "Kind Words"
        [[params.kind_words.items]]
            title = "Happy Cat"
            content = "I am very happy cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Orange Cat"
            content = "I am very orange cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Big Cat"
            content = "I am very big cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Website Cat"
            content = "I am website cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Cat"
            content = "It is just a Cat"
            image = "/images/hero.png"

    [params.contact]
        enable = true
        content = "My inbox is always open"
        btnName = "Mail me"
        btnLink = "mail@gmail.com"
        [params.contact.formspree]
            enable = true
            emailCaption = "Enter your email address"
            messageCaption = "Enter your message here"
            messageRows = 8
        [params.footer.socialNetworks]
            instagram = "https://instagram.com"
            facebook = "https://facebook.com"

    # customScripts = """
    #   <script type="text/javascript"><!-- any script here --></script>
    # """
