baseURL = 'https://example.org'
languageCode = 'en-us'
title = 'Your Photographer'
theme = "hugo-profile"

outputs = { home = ["HTML", "RSS", "JSON"], page = ["HTML", "RSS"] }

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false

[Menus]
    [[Menus.main]]
        identifier = "dropdown"
        title = "Gallery dropdown menu"
        name = "Gallery"
        weight = 1
     [[Menus.main]]
        identifier = "dropdown1"
        title = "example dropdown 1"
        name = "example 1"
        url = "/#"
        parent = "dropdown"
        weight = 1
     [[Menus.main]]
        identifier = "dropdown2"
        title = "example dropdown 2"
        name = "example 2"
        url = "/#"
        parent = "dropdown"
        weight = 2

[params]
    title = "Hugo Profile"
    description = "Cool site"
    # staticPath = ""  # The path to serve the static files from
    favicon = "/logo.png"

    useBootstrapCDN = false
    mathjax = false
    # Whether the fade animations on the home page will be enabled
    animate = true

    [params.theme]
        # disableThemeToggle = true
        # defaultTheme = "light" # dark

    [params.font]
        fontSize = "1rem" # default: 1rem
        fontWeight = 400 # default: 400
        lineHeight = 1.5 # default: 1.5
        textAlign = "left" # default: left

    # color preference
    # When using hex codes for colors, quotations must be used along with the # sign
    # [params.color]
    #   textColor = "#343a40"
    #   secondaryTextColor = "#6c757d"
    #   textLinkColor = "#007bff"
    #   backgroundColor = "#eaedf0"
    #   secondaryBackgroundColor = "#64ffda1a"
    #   primaryColor = "#007bff"
    #   secondaryColor = "#f8f9fa"

    #   [params.color.darkmode]
    #     textColor = "#e4e6eb"
    #     secondaryTextColor = "#b0b3b8"
    #     textLinkColor = "#ffffff"
    #     backgroundColor = "#18191a"
    #     secondaryBackgroundColor = "#212529"
    #     primaryColor = "#ffffff"
    #     secondaryColor = "#212529"

    # If you want to customize the menu, you can change it here
    [params.navbar]
        align = "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
        brandLogo = "/logo.png"
        # showBrandLogo = false # Show brand logo in nav bar | default is true
        brandName = "Your Photograph" # Brand name for the brand | default is the title variable
        [params.navbar.stickyNavBar]
            enable = true
            showOnScrollUp = true
        enableSeparator = false
        [params.navbar.menus]
            disableAbout = false
            disableAchievements = false
            disableContact = false

    # Hero
    [params.hero]
        enable = true
        intro = "Hi, my name is"
        title = "Isabella."
        subtitle = "I am your photographer"
        content = "A passionate photographer"
        image = "/images/hero.svg"
        [params.hero.bottomImage]
            enable = true

        [params.hero.button]
            enable = true
            name = "Resume"
            url = "#"
            download = true
            newPage = false

    # About
    [params.about]
        enable = true
        title = "About Me"
        image = "/images/me.png"
        content = "A passionate photographer"
        [params.about.skills]
            enable = true
            title = "Here are a few technologies I've been working with recently:"
            items = ["Dark", "Light", "Express"]

    # Achievements
    [params.achievements]
        enable = true
        # title = "Custom Name"
        [[params.achievements.items]]
            title = "Google kickstart runner"
            content = "I solved all problems with optimal solution."
            url = "https://example.com"
            image = "/images/achievment.jpg"
        [[params.achievements.items]]
            title = "Facebook Hackathon Winner"
            content = "Developed a product using Artificial Intelligence."
            image = "/images/achievment.jpg"
        [[params.achievements.items]]
            title = "Hugo Profile"
            content = "Developed a theme and getting 1K+ downloads per month."
            url = "https://github.com/gurusabarish/hugo-profile"
            image = "/images/achievment.jpg"
        [[params.achievements.items]]
            title = "Microsoft Imagine Runner"
            content = "We are developed a product which can help others."
        [[params.achievements.items]]
            title = "Google Summer of Code"
            content = "Contributed to a open source project."
            url = "https://example.com"

    # Contact
    [params.contact]
        enable = true
        # title = "Custom Name"
        content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
        btnName = "Mail me"
        btnLink = "mailto:gurusabarisha@gmail.com"
        [params.contact.formspree]
            enable = true
            emailCaption = "Enter your email address"
            messageCaption = "Enter your message here"
            messageRows = 8

    # [params.footer]
    #     [params.footer.recentPosts]
    #         path = "blogs"
    #         count = 3
    #         title = "Recent Posts"
    #         enable = true
    #         disableFeaturedImage = false
        [params.footer.socialNetworks]
            github = "https://github.com"
            linkedin = "https://linkedin.com"
            twitter = "https://twitter.com"
            instagram = "https://instagram.com"
            facebook = "https://facebook.com"

    # List pages like blogs and posts
    [params.listPages]
        disableFeaturedImage = false

    # Single pages like blog and post
    [params.singlePages]
        socialShare = true
        [params.singlePages.readTime]
            enable = true
            content = "min read"
        [params.singlePages.scrollprogress]
            enable = true
        [params.singlePages.tags]
            openInNewTab = true

    # For translations
    [params.terms]
        read = "Read"
        toc = "Table Of Contents"
        copyright = "All rights reserved"
        pageNotFound = "Page not found"
        emailText = "Check out this site"

    [params.datesFormat]
        article = "Jan 2, 2006"
        articleList = "Jan 2, 2006"
        articleRecent = "Jan 2, 2006"

    # customScripts = """
    #   <script type="text/javascript"><!-- any script here --></script>
    # """
