baseURL = "http://localhost/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Your Photographer'
    weight = 1
    [languages.en.params.about]
        enable = true
        title = "About Me"
        image = "/images/about.jpeg"
        content = """Erricson is the only photographer with a Royal Warrant given by HRH Prince of Wales in the United Kingdom. Born in Canada, Erricson first learned to develop and print photographs on the kitchen table at home, with his mother.
        \nErricson has worked closely with Best magazine since 1990.
        \nHis previous subjects include Her Majesty The Queen, Bill Clinton, President Mikhail Gorbachev, Baroness Thatcher, Lucian Freud, Victoria Beckham, and Michael Jackson. In 2005, Erricson photographed the wedding of HRH Prince of Wales to Camilla Parker-Bowles, and then in 2011, he photographed the wedding of HRH Prince William to Catherine Middleton. Similarly, Erricson is famous for taking an official portrait of Prince Charles, Prince of Wales, to mark his 60th birthday in 2008."""
        [languages.en.params.about.skills]
            enable = true
            title = "Here are styles I are working with:"
            items = ["Nature", "Landscape", "Portrait", "Wedding"]
    [languages.en.params.kind_words]
        enable = true
        title = "Kind Words"
        [[languages.en.params.kind_words.items]]
            title = "Happy Cat"
            content = "I am very happy cat"
            image = "/images/Dafoe.jpg"
        [[languages.en.params.kind_words.items]]
            title = "Orange Cat"
            content = "I am very orange cat"
            image = "/images/Nixon.jpg"
        [[languages.en.params.kind_words.items]]
            title = "Big Cat"
            content = "I am very big cat"
            image = "/images/Shinzō_Abe.jpg"
    [languages.en.params.services]
        enable = true
        title = "Services"

  [languages.uk]
    contentDir = 'content/uk'
    languageCode = 'uk-UA'
    languageName = 'Українська'
    title = 'Ваш фотограф'
    weight = 2
    [languages.uk.params.about]
        enable = true
        title = "Про мене"
        image = "/images/me.png"
        content = "Крутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кіт\nКрутий кітКрутий кітКрутий кіт\nКрутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кітКрутий кіт"
        [languages.uk.params.about.skills]
            enable = true
            title = "Ось кілька котів, з якими я працював:"
            items = ["Темний кіт", "Світлий кіт", "Помаранчевий кіт"]

    [languages.uk.params.kind_words]
        enable = true
        title = "Добрі слова"
        [[languages.uk.params.kind_words.items]]
            title = "Щасливий кіт"
            content = "Я дуже щасливий кіт"
            image = "/images/hero.png"
        [[languages.uk.params.kind_words.items]]
            title = "Помаранчевий кіт"
            content = "Я дуже помаранчевий кіт"
            image = "/images/hero.png"
        [[languages.uk.params.kind_words.items]]
            title = "Великий кіт"
            content = "Я дуже великий кіт"
            image = "/images/hero.png"

    [languages.uk.params.services]
        enable = true
        title = "Послуги"

[outputs]
    home = ['html', 'json']
    page = ['html']
    rss = ['rss']
    section = ['html']
    taxonomy = ['html']
    term = ['html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false

[Menus]
    [[Menus.main]]
        identifier = "dropdown"
        title = "galleryDropdownTitle"
        name = "galleryDropdownName"
        weight = 1
    [[Menus.main]]
        identifier = "oc_dropdown1"
        title = "orangeCatsDropdownTitle"
        name = "orangeCatsDropdownName"
        url = "/gallery/orange_cats/"
        parent = "dropdown"
        weight = 1
    [[Menus.main]]
        identifier = "col_dropdown2"
        title = "coolOrangeCatsDropdownTitle"
        name = "coolOrangeCatsDropdownName"
        url = "/gallery/cool_orange_cats/"
        parent = "dropdown"
        weight = 2

[params]
    description = "Cool site"
    favicon = "/logo.png"

    useBootstrapCDN = false
    animate = true

    [params.services]
        enable = true
        title = "Послуги"

    [params.font]
        fontSize = "1rem"
        fontWeight = 400
        lineHeight = 1.5
        textAlign = "left"

    [params.color]
        textColor = "#343a40"
        secondaryTextColor = "#6c757d"
        textLinkColor = "#007bff"
        backgroundColor = "#eaedf0"
        secondaryBackgroundColor = "#64ffda1a"
        primaryColor = "#007bff"
        secondaryColor = "#f8f9fa"

    [params.navbar]
        align = "ms-auto"
        brandLogo = "/logo.png"
        brandName = "{{ T `navbar_brandName` }}"
        [params.navbar.stickyNavBar]
            enable = true
            showOnScrollUp = true
        enableSeparator = false
        [params.navbar.menus]
            disableAbout = false
            disableKind_words = false
            disableContact = false

    [params.hero]
        enable = true
        intro = "{{ T `hero_intro` }}"
        title = "{{ T `hero_title` }}"
        subtitle = "{{ T `hero_subtitle` }}"
        content = "{{ T `hero_content` }}"
        image = "/images/hero.png"
        [params.hero.bottomImage]
            enable = true

    [params.contact]
        enable = true
        title = "{{ T `contact_title` }}"
        content = "{{ T `contact_content` }}"
        btnName = "{{ T `contact_btnName` }}"
        btnLink = "{{ T `contact_btnLink` }}"
        [params.contact.formspree]
            enable = true
            emailCaption = "{{ T `contact_formspree_messageCaption` } "
            messageCaption = "{{ T `contact_formspree_messageCaption` } "
            messageRows = 8
        [params.footer.socialNetworks]
            instagram = "https://instagram.com"
            facebook = "https://facebook.com"


    # customScripts = """
    #   <script type="text/javascript"><!-- any script here --></script>
    # """
