baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Your Photographer'

outputs = { home = ["HTML", "RSS", "JSON"], page = ["HTML", "RSS"] }
disableAliases = true
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false

[Menus]
    [[Menus.main]]
        identifier = "dropdown"
        title = "Gallery dropdown menu"
        name = "Gallery"
        weight = 1
     [[Menus.main]]
        identifier = "oc_dropdown1"
        title = "Orange Cats Dropdown"
        name = "Orange Cats"
        url = "/gallery/orange-cats/"
        parent = "dropdown"
        weight = 1
     [[Menus.main]]
        identifier = "col_dropdown2"
        title = "Cool Orange Cats Dropdown"
        name = "Cool Orange Cats"
        url = "/gallery/cool_orange_cats/"
        parent = "dropdown"
        weight = 2

[params]
    title = "Hugo Profile"
    description = "Cool site"
    favicon = "/logo.png"

    useBootstrapCDN = false
    mathjax = false
    # Whether the fade animations on the home page will be enabled
    animate = true

    [params.font]
        fontSize = "1rem" # default: 1rem
        fontWeight = 400 # default: 400
        lineHeight = 1.5 # default: 1.5
        textAlign = "left" # default: left


    [params.color]
        textColor = "#343a40"
        secondaryTextColor = "#6c757d"
        textLinkColor = "#007bff"
        backgroundColor = "#eaedf0"
        secondaryBackgroundColor = "#64ffda1a"
        primaryColor = "#007bff"
        secondaryColor = "#f8f9fa"

   [params.color.darkmode]
        textColor = "#e4e6eb"
        secondaryTextColor = "#b0b3b8"
        textLinkColor = "#ffffff"
        backgroundColor = "#18191a"
        secondaryBackgroundColor = "#212529"
        primaryColor = "#ffffff"
        secondaryColor = "#212529"

    # If you want to customize the menu, you can change it here
    [params.navbar]
        align = "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
        brandLogo = "/logo.png"
        # showBrandLogo = false # Show brand logo in nav bar | default is true
        brandName = "Your Photograph" # Brand name for the brand | default is the title variable
        [params.navbar.stickyNavBar]
            enable = true
            showOnScrollUp = true
        enableSeparator = false
        [params.navbar.menus]
            disableAbout = false
            disableKind_words = false
            disableContact = false

    # Hero
    [params.hero]
        enable = true
        intro = "Hi, i am"
        title = "Cat."
        subtitle = "I am your cat"
        content = "A cool cat"
        image = "/images/hero.png"
        [params.hero.bottomImage]
            enable = true

        [params.hero.button]
            enable = true
            name = "Resume"
            url = "#"
            download = true
            newPage = false

    # About
    [params.about]
        enable = true
        title = "About Me"
        image = "/images/me.png"
        content = "Cool catCool catCool catCool catCool catCool catCool catCool cat\nCool catCool catCool cat\nCool catCool catCool catCool catCool catCool catCool catCool catCool cat"
        [params.about.skills]
            enable = true
            title = "\nHere are a few cat I am been working with:"
            items = ["Dark cat", "Light cat", "Orange cat"]

    # Kind Words
    [params.kind_words]
        enable = true
        title = "Kind Words"
        [[params.kind_words.items]]
            title = "Happy Cat"
            content = "I am very happy cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Orange Cat"
            content = "I am very orange cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Big Cat"
            content = "I am very big cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Website Cat"
            content = "I am website cat"
            image = "/images/hero.png"
        [[params.kind_words.items]]
            title = "Cat"
            content = "It is just a Cat"
            image = "/images/hero.png"

    # Contact
    [params.contact]
        enable = true
        # title = "Custom Name"
        content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
        btnName = "Mail me"
        btnLink = "vladpuku@gmail.com"
        [params.contact.formspree]
            enable = true
            emailCaption = "Enter your email address"
            messageCaption = "Enter your message here"
            messageRows = 8

        [params.footer.socialNetworks]
            x = "https://x.com"
            instagram = "https://instagram.com"
            facebook = "https://facebook.com"

    # List pages like blogs and posts
    [params.listPages]
        disableFeaturedImage = false

    # For translations
    [params.terms]
        read = "Read"
        toc = "Table Of Contents"
        copyright = "All rights reserved"
        pageNotFound = "Page not found"
        emailText = "Check out this site"

    [params.datesFormat]
        article = "Jan 2, 2006"
        articleList = "Jan 2, 2006"
        articleRecent = "Jan 2, 2006"

    # customScripts = """
    #   <script type="text/javascript"><!-- any script here --></script>
    # """
