baseURL = "http://localhost:1313/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Your Photographer'
    weight = 1
    [languages.en.params.about]
        enable = true
        title = "About Me"
        image = "/images/about.jpeg"
        content = """Ericson is the only photographer with a Royal Warrant given by HRH Prince of Wales in the United Kingdom. Born in Canada, Ericson first learned to develop and print photographs on the kitchen table at home, with his mother.
        \nEricson has worked closely with Best magazine since 1990.
        \nHis previous subjects include Her Majesty The Queen, Bill Clinton, President Mikhail Gorbachev, Baroness Thatcher, Lucian Freud, Victoria Becharm, and Michael Jackson. In 2005, Ericson photographed the wedding of HRH Prince of Wales to Camilla Parker-Bowels, and then in 2011, he photographed the wedding of HRH Prince William to Catherine Middleton. Similarly, Ericson is famous for taking an official portrait of Prince Charles, Prince of Wales, to mark his 60th birthday in 2008."""
        [languages.en.params.about.skills]
            enable = true
            title = "Here are styles I are working with:"
            items = ["Nature", "Landscape", "Portrait", "Wedding"]
    [languages.en.params.kind_words]
        enable = true
        title = "Kind Words"
        [[languages.en.params.kind_words.items]]
            title = "William Dafoe"
            content = "Ericson is an amazing and talented photographer!"
            image = "/images/Dafoe.jpg"
        [[languages.en.params.kind_words.items]]
            title = "Richard Nixon"
            content = "Ericson is an amazing and talented photographer!"
            image = "/images/Nixon.jpg"
        [[languages.en.params.kind_words.items]]
            title = "Shinzo Abe"
            content = "Ericson is an amazing and talented photographer!"
            image = "/images/Shinzo_Abe.jpg"
    [languages.en.params.services]
        enable = true
        title = "Services"

  [languages.uk]
    contentDir = 'content/uk'
    languageCode = 'uk-UA'
    languageName = 'Українська'
    title = 'Ваш фотограф'
    weight = 2
    [languages.uk.params.about]
        enable = true
        title = "Про мене"
        image = "/images/about.jpeg"
        content = """Еріксон є єдиним фотографом, який має Королівський Ордер, виданий Його Високістю Принцем Уельським у Сполученому Королівстві. Еріксон, який народився в Канаді, вперше навчився проявляти та друкувати фотографії на кухонному столі вдома разом зі своєю матір’ю.
        \nЕріксон тісно співпрацює з журналом Best з 1990 року.
        \nЙого попередні піддані включають Її Величність Королеву, Білла Клінтона, Президента Михайла Горбачова, Баронесу Тетчер, Лючіана Фрейда, Вікторію Бешарм і Майкла Джексона. У 2005 році Еріксон сфотографував весілля Його Високості Принца Уельського з Каміллою Паркер-Боулс, а потім у 2011 році він сфотографував весілля Його Високості Принца Вільяма з Кетрін Міддлтон. Крім того, Еріксон відомий тим, що зробив офіційний портрет принца Чарльза, принца Уельського, до його 60-річчя в 2008 році."""
        [languages.uk.params.about.skills]
            enable = true
            title = "Ось стилі, з якими я працюю:"
            items = ["Природа", "Пейзаж", "Портрет", "Весілля"]

    [languages.uk.params.kind_words]
        enable = true
        title = "Відгуки"
        [[languages.uk.params.kind_words.items]]
            title = "Віллем Дефо"
            content = "Еріксон - чудовий і талановитий фотограф!"
            image = "/images/Dafoe.jpg"
        [[languages.uk.params.kind_words.items]]
            title = "Річард Ніксон"
            content = "Еріксон - чудовий і талановитий фотограф!"
            image = "/images/Nixon.jpg"
        [[languages.uk.params.kind_words.items]]
            title = "Абе Сіндзо"
            content = "Еріксон - чудовий і талановитий фотограф!"
            image = "/images/Shinzo_Abe.jpg"

    [languages.uk.params.services]
        enable = true
        title = "Послуги"

[outputs]
    home = ['html', 'json']
    page = ['html']
    rss = ['rss']
    section = ['html']
    taxonomy = ['html']
    term = ['html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false

[Menus]
    [[Menus.main]]
        identifier = "dropdown"
        title = "galleryDropdownTitle"
        name = "galleryDropdownName"
        weight = 1
    [[Menus.main]]
        identifier = "oc_dropdown1"
        title = "firstDropdownTitle"
        name = "firstDropdownName"
        url = "/gallery/peoples/"
        parent = "dropdown"
        weight = 1
    [[Menus.main]]
        identifier = "col_dropdown2"
        title = "secondDropdownTitle"
        name = "secondDropdownName"
        url = "/gallery/cats/"
        parent = "dropdown"
        weight = 2

[params]
    description = "Cool site"
    favicon = "/logo.png"

    animate = true

    [params.services]
        enable = true
        title = "Послуги"

    [params.font]
        fontSize = "1rem"
        fontWeight = 400
        lineHeight = 1.5
        textAlign = "left"

    [params.color]
        textColor = "#343a40"
        secondaryTextColor = "#6c757d"
        textLinkColor = "#007bff"
        backgroundColor = "#eaedf0"
        secondaryBackgroundColor = "#64ffda1a"
        primaryColor = "#007bff"
        secondaryColor = "#f8f9fa"

    [params.navbar]
        align = "ms-auto"
        brandLogo = "/logo.png"
        brandName = "{{ T `navbar_brandName` }}"
        enableSeparator = false

    [params.hero]
        enable = true
        intro = "{{ T `hero_intro` }}"
        title = "{{ T `hero_title` }}"
        subtitle = "{{ T `hero_subtitle` }}"
        content = "{{ T `hero_content` }}"
        image = "/images/hero.png"
        [params.hero.bottomImage]
            enable = true

    [params.contact]
        enable = true
        title = "{{ T `contact_title` }}"
        content = "{{ T `contact_content` }}"
        btnName = "{{ T `contact_btnName` }}"
        btnLink = "{{ T `contact_btnLink` }}"
        [params.contact.formspree]
            enable = true
            emailCaption = "{{ T `contact_formspree_messageCaption` } "
            messageCaption = "{{ T `contact_formspree_messageCaption` } "
            messageRows = 8
        [params.footer.socialNetworks]
            instagram = "https://instagram.com"
            facebook = "https://facebook.com"
